### ISSUE TITLE
Error on fresh install: Something went wrong during the Sign up OAuth flow

### ISSUE THREAD

**Issue by paulclark** [clerkinc/t3-turbo-and-clerk#14]
[Original issue filed on create-t3-turbo](https://github.com/t3-oss/create-t3-turbo/issues/33#issuecomment-1366304752), filing here by request.

I tried a fresh clone of this repo + a fresh clerk.dev account, copied API keys into `.env` + `_app.tsx`, and enabled Discord in the Clerk dashboard, and am getting the following error attempting to Sign Up using iOS Simulator.

> @acme/expo:dev: LOG error signing in Something went wrong during the Sign in OAuth flow. Please ensure that all sign in requirements are met.

* Screenshots in [linked issue](https://github.com/t3-oss/create-t3-turbo/issues/33#issuecomment-1366304752) - reported as Sign In, but both actions error.
* [Video of issue](https://www.loom.com/share/fa13e36bfcc34cb5ad5c57cd532b39ce)

Thanks for offering this repo, excited to get it up and running :+1:

**Comment by perkinsjr** [comment]
Hi Paul!

Thanks for reaching out. I tried to recreate this but could not. Using a fresh Clerk and fresh t3-turbo account. 

Can you update the SignUp component Line 45 to print out the signUp object: 
```
await signUp.reload({ rotatingTokenNonce });
      console.log(
        JSON.stringify(signUp.verifications.externalAccount, null, 2),
      );
      const { createdSessionId } = signUp;
```

Then provide the result of the logging. This error should only occur when the user attempts to sign up after already having an account.

**Comment by paulclark** [comment]
I got it working 🙂 I chose to require Phone Number when creating my Clerk application, which was the cause of the error. Disabling that setting in the dashboard fixed it.

Relevant part of the full `signUp` object that helped me resolve:

```
@acme/expo:dev:  LOG  {
@acme/expo:dev:   "pathRoot": "/client/sign_ups",
@acme/expo:dev:   "status": "missing_requirements",
@acme/expo:dev:   "requiredFields": [
@acme/expo:dev:     "email_address",
@acme/expo:dev:     "phone_number"
@acme/expo:dev:   ],
@acme/expo:dev:   "optionalFields": [
@acme/expo:dev:     "oauth_discord",
@acme/expo:dev:     "oauth_twitter",
@acme/expo:dev:     "oauth_linkedin",
@acme/expo:dev:     "oauth_apple",
@acme/expo:dev:     "oauth_google"
@acme/expo:dev:   ],
@acme/expo:dev:   "missingFields": [
@acme/expo:dev:     "phone_number"
@acme/expo:dev:   ],
@acme/expo:dev:   "unverifiedFields": [],
...
```

To help other folks avoid potentially tripping up, I'd suggest updating the [setup instructions](https://github.com/clerkinc/t3-turbo-and-clerk#clerk-dashboard-setup) to be explicit about default settings for the Clerk application, and/or linking docs to handling other required fields if toggled on. Thanks again for the troubleshooting assistance!

**Comment by james1050** [comment]
Thanks for the comment about problems with requiring Phone Number Paul! That saved me some time. I wasn't getting any error logged, but sign-up was silently not completing. Removing Phone Number in Clerk settings fixed it.

**Comment by akinwol** [comment]
This just saved me as well. Very silly, I was scratching my head trying to figure out the issue since there was no error.  Docs should definitely be updated.
