### ISSUE TITLE
vercel deployment fails @clerk/nextjs/api

### ISSUE THREAD

**Issue by Flowko** [clerkinc/t3-turbo-and-clerk#25]
![image](https://user-images.githubusercontent.com/35883748/213817378-83f216bf-4dec-4f25-865e-7241c680110e.png)

it cant find those modules inside of `@clerk/nextjs` ( fine: packages/api/src/context.ts )

![image](https://user-images.githubusercontent.com/35883748/213817653-59616a29-7052-4bb4-abf5-6bf1de311be8.png)

**Comment by perkinsjr** [comment]
Hi, I cannot recreate this with the latest versions of the template. 

Steps:

1. Cloned repo
2. Pushed repo to a new project
3. deployed to vercel adding my .env 
4. Successful build.

Can you please verify that pnpm is installing correctly through turbo repo / make sure you have the latest version of Clerk that released today.

**Comment by Flowko** [comment]
yeah, just saw u committed a new change, will check that now

**Comment by perkinsjr** [comment]
I did but also checked with the previous version and it was also working

**Comment by Flowko** [comment]
shit, yeah didnt see those dots at the end, its passing that now i believe
![image](https://user-images.githubusercontent.com/35883748/213820200-a5d3a3fc-3b12-422e-a5a6-7078b3e26857.png)

also worth mentioning, 

![image](https://user-images.githubusercontent.com/35883748/213820265-7ded3f38-88fc-4dd9-8b35-4beae4c773b8.png)

![image](https://user-images.githubusercontent.com/35883748/213820242-a1b33d4e-8d36-4776-bdbb-682625d0ff44.png)

**Comment by Flowko** [comment]
and no, removing those dots didn't do anything :(

**Comment by perkinsjr** [comment]
This was updated recently by the T3 core team, so we are inline with them at this time.

I can talk to them about updating all of them. the only difference is Clerk vs Next Auth

**Comment by perkinsjr** [comment]
Can you attempt to create a new project? That error would only appear if the module is not installed at build time through pnpm

**Comment by Flowko** [comment]
yeah sure will try it now

**Comment by Flowko** [comment]
still same thing, what i dont understand is that im getting the same thing on vscode 
Cannot find module '@clerk/nextjs/server' or its corresponding type declarations
, using same clerk package versions and all

**Comment by perkinsjr** [comment]
No I don't get any errors when using `pnpm i` in the root directory. 

Can you confirm there is a `node_modules` folder in your `apps/nextjs`

**Comment by Flowko** [comment]
yes there's node_modules inside it

**Comment by perkinsjr** [comment]
Can you confirm that there is `@clerk/nextjs` in the `app/node_modules` folder?

**Comment by Flowko** [comment]
u mean `apps/nextjs/node_modules`  yes there is, also those server/api js files as well

**Comment by perkinsjr** [comment]
So there should be:

root directory `node_modules` this should have `@clerk/packages`, the `apps/nextjs` folder should have `node_modules` without any clerk modules in it but gets a share from the root `node_modules`. 
![image](https://user-images.githubusercontent.com/45409975/213823220-434cfea2-6400-4422-848b-9138209d8164.png)

**Comment by Flowko** [comment]
yeah i dont have the same thing:

Root Dir:

![image](https://user-images.githubusercontent.com/35883748/213823701-4cc72dc9-e35d-45e5-abb6-d1f3be3845c8.png)

Nextjs Dir:

![image](https://user-images.githubusercontent.com/35883748/213823763-bc2698e6-3df6-4111-8a97-02a2b5c8f03f.png)

i havent updated the root package of the project, how could that happen ?

**Comment by perkinsjr** [comment]
Can you tell me what version of pnpm you are using?

**Comment by Flowko** [comment]
7.25.1

**Comment by perkinsjr** [comment]
I just updated pnpm  to that version and still can run, and build the project. Can you run locally?

**Comment by Flowko** [comment]
it was working fine before, but now it doesnt, i'll try to clear my pnpm cache try a clean install once again, hopefully
![image](https://user-images.githubusercontent.com/35883748/213824829-2bf26ab0-e661-4173-b181-3566ea3972c3.png)

**Comment by perkinsjr** [comment]
All these points to something specific to your machine causing pnpm to act strange. Just got out my secondary MacBook which has never had this project on. It is also working as expected

**Comment by Flowko** [comment]
yeah thanks for your time, i'll update here if i resolve this issue
