### ISSUE TITLE
Unable to add additional OAuth provider

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [clerkinc/t3-turbo-and-clerk#32]
I've been reading through the clerk docs for authentications and social connections but I can't make the base app work.
I tried adding Google Sign In/up and it just doesn't even create users.

https://user-images.githubusercontent.com/74371045/214753021-d4d3e333-3f04-4741-8a65-60751185d41a.mov

### Logs from the above demo
<img width="765" alt="Screenshot 2023-01-25 at 22 29 56" src="https://user-images.githubusercontent.com/74371045/214752899-9c03a9e5-0c37-44a8-a868-dddf2de35bf8.png">

the app should navigate to the `SignedIn screen`.

- I only added this extra code (`SignUp`) I got from https://github.com/clerkinc/clerk-expo-starter/blob/main/components/SignUpWithOauth.tsx

``` typescript
import React from "react";
import { Text, TouchableOpacity } from "react-native";
import { useSignUp } from "@clerk/clerk-expo";
import { log } from "../logger";
import { styles } from "./Styles";
import * as AuthSession from "expo-auth-session";

export function SignUpWithOauth() {
  const { signUp, setSession, isLoaded } = useSignUp();

  const onPress = React.useCallback(async () => {
    if (!isLoaded) {
      return;
    }

    try {
      // Create a redirect url for the current platform and environment.
      //
      // This redirect URL needs to be whitelisted for your instance via
      // https://reference.clerk.dev/reference/backend-api-reference/redirect-urls#add-a-redirect-url
      //
      // For more information go to:
      // https://docs.expo.dev/versions/latest/sdk/auth-session/#authsessionmakeredirecturi
      const redirectUrl = AuthSession.makeRedirectUri({
        path: "/oauth-native-callback",
      });

      await signUp.create({
        strategy: "oauth_google",
        redirectUrl,
      });

      const {
        verifications: {
          externalAccount: { externalVerificationRedirectURL },
        },
      } = signUp;

      const result = await AuthSession.startAsync({
        authUrl: externalVerificationRedirectURL!.toString(),
        returnUrl: redirectUrl,
      });

      // @ts-ignore
      const { type, params } = result || {};

      // Check all the possible AuthSession results
      // https://docs.expo.dev/versions/latest/sdk/auth-session/#returns-7
      if (type !== "success") {
        throw "Something went wrong during the OAuth flow. Try again.";
      }

      // Get the rotatingTokenNonce from the redirect URL parameters
      const { rotating_token_nonce: rotatingTokenNonce } = params;

      // Use it once to reload the complete sign up object
      await signUp.reload({ rotatingTokenNonce });

      const { createdSessionId } = signUp;

      if (!createdSessionId) {
        throw "Something went wrong during the Sign up OAuth flow. Please ensure that all sign up requirements are met.";
      }

      await setSession(createdSessionId);
      return;
    } catch (err: any) {
      log("Error:> " + err?.status || '');
      log("Error:> " + err?.errors ? JSON.stringify(err.errors) : err);
    }
  }, []);

  return (
    <TouchableOpacity
      style={{ ...styles.secondaryButton, marginBottom: 20 }}
      onPress={onPress}
    >
      <Text style={styles.secondaryButtonText}>Sign up with Google</Text>
    </TouchableOpacity>
  );
}
```

**Comment by AlvaroAquijeDiaz** [comment]
I've actually setup the google auth on clerk as well and it wasn't working for me, will try again

**Comment by perkinsjr** [comment]
If it doesn't work please provide the logs in text format so I can read them versus a screen shot.

**Comment by perkinsjr** [comment]
Closing this asa a none issue with the template but the code itself.

Please feel free to re-open or join the Discord for real time support.

**Comment by perkinsjr** [comment]
I have plans to add some more logic here; however, by default username is not enabled unless you select it. Which is why we aren't catching usernames in the signup hook errors. 

Below this is the dashboard as you create an app as you can see this is turned off.

![image](https://user-images.githubusercontent.com/45409975/215521128-1852b972-a28a-4aaa-9320-34b441cf5c23.png)

**Comment by shadown125** [comment]
Yeah, I see you are right. I created my first project like 1-2 weeks ago when you switch 'frontendApi' to 'publishable_key' and I had same settings as you posted. Still, I got username required per default. Probably was a small period of time when a new Project was created with username as required per default. Now seems everything to be fine but still it would be nice that devs could get Logs and debug such issues by yourself :)

**Comment by AlvaroAquijeDiaz** [comment]
hey @shadown125 how is your setup for oauth_google in the repo and clerk project, if you don't mind sharing, I'm still having some weird issues

**Comment by perkinsjr** [comment]
please re open the ticket, with what you have tried. what errors you are receiving. what your code looks like etc, or join our Discord for direct support.

**Comment by shadown125** [comment]
Hello @AlvaroAquijeDiaz 

I can't share repo because it's my private project, but it is the same Component what you get from Clerk turbo repo.

You only need to change signIn.create() method from useSignIn() hook to strategy: 'oauth_google'.

It will look like this:  `await signIn.create({
                strategy: "oauth_google",
                redirectUrl,
            });`
            
After that, you just need to create a new Project in clerk.dev and link your published key which is under API keys to your project (app.config.ts => there is CLERK_PUBLISHABLE_KEY).

Then sign in with Google and others, oauth providers should work without problems.

**Comment by AlvaroAquijeDiaz** [comment]
quick comment, as @shadown125 said the problem was that the `username` field was turned on in the clerk project, disabling it allows signIn work as expected
