### ISSUE TITLE
Pnpm run dev returns node_module is missing

### ISSUE THREAD

**Issue by adonis-albelda** [clerkinc/t3-turbo-and-clerk#34]
Tried to follow everything written in the docs. I've seen already the node_modules folder inside root folder. Then when I executed this command `pnpm dev` this is  the result .
![image](https://user-images.githubusercontent.com/64679741/214809147-f07d3929-ca4e-4347-b9fc-5735a547dab9.png)

**Comment by perkinsjr** [comment]
hey, thanks for the report 

Can you give me your:

PNPM version
Xcode tools version

**Comment by adonis-albelda** [comment]
Hey, no Xcode installed. But for PNPM, it's v7.26

**Comment by perkinsjr** [comment]
Based on the error Expo needs to run in interactive mode 

cd apps/expo

npm run dev 

follow the instructions and then you should be able to launch

**Comment by Dale-Black** [comment]
I have xcode installed but I stilled get this error every time I try to do `pnpm dev` inside of apps/expo

```
daleblack@Dales-MacBook-Air expo % pnpm dev

> @acme/expo@0.1.0 dev /Users/daleblack/Library/CloudStorage/GoogleDrive-djblack@uci.edu/My Drive/dev/bible-mem/apps/expo
> expo start --ios

Starting project at /Users/daleblack/Library/CloudStorage/GoogleDrive-djblack@uci.edu/My Drive/dev/bible-mem/apps/expo
Some dependencies are incompatible with the installed expo version:
  @shopify/flash-list@1.4.0 - expected version: 1.3.1
  expo-auth-session@3.7.3 - expected version: ~3.8.0
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0
Starting Metro Bundler
? Xcode needs to be installed (don't worry, you won't have to use it), would you like to continue to the App Store? › (Y/n)
```

**Comment by perkinsjr** [comment]
just run npm run dev from apps/expo and follow the install prompt. you XCode and Xcode command tools

**Comment by Dale-Black** [comment]
I already did that and I downloaded xcode from the app store.

**Comment by perkinsjr** [comment]
if you run npm run start from app/expo and press i what happens?

> I already did that and I downloaded xcode from the app store.

**Comment by Dale-Black** [comment]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/62632960/215295047-2bd6b228-4472-476f-95da-ec5ca5330e93.png">

**Comment by Dale-Black** [comment]
But I already have xcode and I've opened up the simulator manually

**Comment by Dale-Black** [comment]
and `pnpm dev` from the root dir gives this 
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/62632960/215295103-020f15a3-7edb-4e37-a427-a0092a070c75.png">

**Comment by perkinsjr** [comment]
What shows in XCODE when you open it and go to /settings/locations under Command Line Tools?

![image](https://user-images.githubusercontent.com/45409975/215295267-cde943b2-4f16-4899-8ae5-41f041b5c54c.png)

**Comment by Dale-Black** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/62632960/215295287-f38d8611-7209-40ae-aba9-09f209040612.png">

**Comment by Dale-Black** [comment]
Ahhh that might be the problem, there was no app for the command line tools

**Comment by Dale-Black** [comment]
Looks like things are progressing after updating that!

**Comment by perkinsjr** [comment]
Yup. Xcode Command Line Tools are required for simulator to run from the terminal.

Closing this as the fix is to install XCode + Command tools properly
