### ISSUE TITLE
routers return undefined data

### ISSUE THREAD

**Issue by Seo-the-platinum** [clerkinc/t3-turbo-and-clerk#36]
I apologize in advance if I am missing something obvious, very new to the t3-stack in general.  I added a test row in my db but the browser and ios simulator are getting a 500 error. Prisma Studio shows the correct data, but I am unable to retrieve it. Other than the .env, everything is a clone of the template.

**Prisma Studio**
<img width="1920" alt="Screenshot 2023-01-26 at 1 27 46 PM" src="https://user-images.githubusercontent.com/31635008/214957743-f3b5a4df-0329-4ea3-be27-e5cc050655b5.png">

**Error when trying to get schema.prisma**
<img width="1920" alt="Screenshot 2023-01-26 at 1 28 14 PM" src="https://user-images.githubusercontent.com/31635008/214957785-62630e6a-0576-4957-a3c8-338773e65ac3.png">

**Errors in developer tools**
<img width="1920" alt="Screenshot 2023-01-26 at 1 28 23 PM" src="https://user-images.githubusercontent.com/31635008/214957800-ca2a5304-6f2d-47a4-a3c2-bd9ccc6a736a.png">

**Comment by Flowko** [comment]
did u run either of `pnpm db-generate` or `pnpm db-push` ?

**Comment by Seo-the-platinum** [comment]
I ran `pnpm db-push` and just tried `pnpm db-generate` but same result

**Comment by Seo-the-platinum** [comment]
I ended up deleting the repo and cloned it again and it fixed it. Thanks for your help
