### ISSUE TITLE
Fetching Expo Go fails

### ISSUE THREAD

**Issue by blakegreendev** [clerkinc/t3-turbo-and-clerk#37]
xcode version 14.2 

`t3-demo on  main [✘!?] via  v18.13.0 took 3s 
❯ pnpm dev              

> t3-turbo-and-clerk@ dev /Users/blake/Github/t3-demo
> turbo dev --parallel

• Packages in scope: @acme/api, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running dev in 5 packages
• Remote caching disabled
@acme/expo:dev: cache bypass, force executing 860b34b36bcfda4c
@acme/nextjs:dev: cache bypass, force executing 48e340e062fd7384
@acme/db:dev: cache bypass, force executing 19db185b1089d767
@acme/nextjs:dev: 
@acme/nextjs:dev: > @acme/nextjs@0.1.0 dev /Users/blake/Github/t3-demo/apps/nextjs
@acme/nextjs:dev: > pnpm with-env next dev
@acme/nextjs:dev: 
@acme/db:dev: 
@acme/db:dev: > @acme/db@0.1.0 dev /Users/blake/Github/t3-demo/packages/db
@acme/db:dev: > pnpm with-env prisma studio --port 5556
@acme/db:dev: 
@acme/expo:dev: 
@acme/expo:dev: > @acme/expo@0.1.0 dev /Users/blake/Github/t3-demo/apps/expo
@acme/expo:dev: > expo start --ios
@acme/expo:dev: 
@acme/db:dev: 
@acme/db:dev: > @acme/db@0.1.0 with-env /Users/blake/Github/t3-demo/packages/db
@acme/db:dev: > dotenv -e ../../.env -- "prisma" "studio" "--port" "5556"
@acme/db:dev: 
@acme/nextjs:dev: 
@acme/nextjs:dev: > @acme/nextjs@0.1.0 with-env /Users/blake/Github/t3-demo/apps/nextjs
@acme/nextjs:dev: > dotenv -e ../../.env -- "next" "dev"
@acme/nextjs:dev: 
@acme/expo:dev: Starting project at /Users/blake/Github/t3-demo/apps/expo
@acme/nextjs:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
@acme/nextjs:dev: warn  - You have enabled experimental feature (transpilePackages) in next.config.mjs.
@acme/nextjs:dev: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
@acme/nextjs:dev: 
@acme/db:dev: Prisma schema loaded from prisma/schema.prisma
@acme/db:dev: Prisma Studio is up on http://localhost:5556
@acme/expo:dev: Some dependencies are incompatible with the installed expo version:
@acme/expo:dev:   @shopify/flash-list@1.4.0 - expected version: 1.3.1
@acme/expo:dev:   expo-auth-session@3.7.3 - expected version: ~3.8.0
@acme/expo:dev: Your project may not work correctly until you install the correct versions of the packages.
@acme/expo:dev: Install individual packages by running npx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0
@acme/expo:dev: Starting Metro Bundler
@acme/nextjs:dev: event - compiled client and server successfully in 336 ms (302 modules)
@acme/nextjs:dev: wait  - compiling...
@acme/nextjs:dev: event - compiled successfully in 25 ms (259 modules)
@acme/expo:dev: › Opening exp://192.168.4.44:19000 on iPhone SE (3rd generation)
@acme/expo:dev: - Fetching Expo Go
@acme/expo:dev: /Users/blake/Github/t3-demo/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78
@acme/expo:dev:                     bar.update(progress, total);
@acme/expo:dev:                         ^
@acme/expo:dev: 
@acme/expo:dev: TypeError: Cannot read properties of null (reading 'update')
@acme/expo:dev:     at Object.onProgress (/Users/blake/Github/t3-demo/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78:25)
@acme/expo:dev:     at onProgress (/Users/blake/Github/t3-demo/node_modules/@expo/cli/build/src/api/rest/wrapFetchWithProgress.js:52:61)
@acme/expo:dev:     at PassThrough.<anonymous> (/Users/blake/Github/t3-demo/node_modules/@expo/cli/build/src/api/rest/wrapFetchWithProgress.js:44:21)
@acme/expo:dev:     at PassThrough.emit (node:events:525:35)
@acme/expo:dev:     at Readable.read (node:internal/streams/readable:539:10)
@acme/expo:dev:     at flow (node:internal/streams/readable:1023:34)
@acme/expo:dev:     at resume_ (node:internal/streams/readable:1004:3)
@acme/expo:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
@acme/expo:dev: 
@acme/expo:dev: Node.js v18.13.0
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/expo:dev: ERROR: command finished with error: command (/Users/blake/Github/t3-demo/apps/expo) pnpm run dev exited (1)
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed.
command (/Users/blake/Github/t3-demo/apps/expo) pnpm run dev exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    22.304s 

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by perkinsjr** [comment]
this error occurs when Expo Go doesn't install correctly and a common issue with Expo

try restarting the terminal / manually opening simulator and run the dev command again

**Comment by BarryJacobs** [comment]
I have the exact same issue but not used expo before, tried the suggestions of restarting the terminal and also having the ios simulator open but no luck so far, did the op solve the issue?

**Comment by perkinsjr** [comment]
@BarryJacobs You can do the following:

```
cd apps/expo

npm run start 

```
this runs in interactive mode, then attempt to open it on the simulator by hitting `i` once you get expo working correctly T3-turbo will work as expected.

**Comment by perkinsjr** [comment]
I am going to close this issue because the issue lies with the machine setup / expo and not with the template itself.
