### ISSUE TITLE
[Question] Native Sign-in with Apple

### ISSUE THREAD

**Issue by vcapretz** [clerkinc/t3-turbo-and-clerk#38]
I just started trying Clerk with Expo, great work you're doing! 

As far as I can see, Clerk doesn't support the native Sign-in with Apple flow (I see it as an OAuth provider, but that wouldn't be the ideal experience in native apps) 

I wonder if that could be an issue from Apple's perspective when publishing to the App Store 😅

Firebase for instance has the `signInWithCredential` method, so I'm still able to have the native Apple login flow using expo-apple-authentication, I wonder if Clerk is planning to add something like that

**Comment by perkinsjr** [comment]
The OAuth sign in a perfectly acceptable way to use Clerk + Apple for users to sign in.

This is how a lot of the industry signs in. We don't have plans currently for native sign in buttons

**Comment by vcapretz** [comment]
@perkinsjr thanks for clarifying 😄 appreciate it
