### ISSUE TITLE
Error: CLERK_PUBLISHABLE_KEY is not defined (Expo iOS(

### ISSUE THREAD

**Issue by ahmadao2214** [clerkinc/t3-turbo-and-clerk#40]
**Describe the bug**
Receive error for expo iOS simulator when running `pnpm dev` on a fresh `t3-turbo-and-clerk` repo:
I copied `CLERK_PUBLISHABLE_KEY` and pasted in `.env`

**To Reproduce**
1. Clone Repo
2. `pnpm i`
3. `pnpm dev`
4. See Error

**Expected behavior**
`t3-turbo-and-clerk` loads on iOS simulator through expo

**Logs**
ERROR  Error: CLERK_PUBLISHABLE_KEY is not defined
ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.

**Screenshots**
![image](https://user-images.githubusercontent.com/8989973/215170642-98128efb-7da4-4eea-9107-8d2b37896ca4.png)

**Desktop (please complete the following information):**
- MAC M1

**Comment by perkinsjr** [comment]
The `CLERK_PUBLISHABLE_KEY` needs to be be in the `apps/expo/src/constants.ts` for expo we aren't using the `.env.` for this and is explained in the README

**Comment by jffry93** [comment]
You can add it to the app.config.ts now.
