### ISSUE TITLE
Expo Go fails to sync

### ISSUE THREAD

**Issue by pencilcheck** [clerkinc/t3-turbo-and-clerk#44]
**Describe the bug**

**To Reproduce**
1. Run `open  -a simulator`
2. Run `pnpm dev` after the installation
3. See error

**Expected behavior**

It worked, launch the app in Simulator and no errors

**Logs**
Please provide logs showing the error.

```
@acme/expo:dev: Some dependencies are incompatible with the installed expo version:
@acme/expo:dev:   @shopify/flash-list@1.4.0 - expected version: 1.3.1
@acme/expo:dev:   expo-auth-session@3.7.3 - expected version: ~3.8.0
@acme/expo:dev:   react@18.2.0 - expected version: 18.1.0
@acme/expo:dev:   react-dom@18.2.0 - expected version: 18.1.0
@acme/expo:dev: Your project may not work correctly until you install the correct versions of the packages.
@acme/expo:dev: Install individual packages by running npx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0 react@18.1.0 react-dom@18.1.0
@acme/db:dev: Prisma schema loaded from prisma/schema.prisma
@acme/expo:dev: Starting Metro Bundler
@acme/db:dev: Prisma Studio is up on http://localhost:5556
@acme/nextjs:dev: event - compiled client and server successfully in 6.4s (302 modules)
@acme/nextjs:dev: wait  - compiling...
@acme/nextjs:dev: event - compiled successfully in 1348 ms (259 modules)
@acme/expo:dev: › Opening exp://10.0.0.13:19000 on iPhone 14 Pro Max
@acme/expo:dev: - Fetching Expo Go
@acme/expo:dev: /project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78
@acme/expo:dev:                     bar.update(progress, total);
@acme/expo:dev:                         ^
@acme/expo:dev:
@acme/expo:dev: TypeError: Cannot read property 'update' of null
@acme/expo:dev:     at Object.onProgress (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/utils/downloadExpoGoAsync.js:78:25)
@acme/expo:dev:     at onProgress (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/api/rest/wrapFetchWithProgress.js:52:61)
@acme/expo:dev:     at PassThrough.<anonymous> (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/api/rest/wrapFetchWithProgress.js:44:21)
@acme/expo:dev:     at PassThrough.emit (events.js:412:35)
@acme/expo:dev:     at PassThrough.Readable.read (internal/streams/readable.js:504:10)
@acme/expo:dev:     at flow (internal/streams/readable.js:987:34)
@acme/expo:dev:     at resume_ (internal/streams/readable.js:968:3)
@acme/expo:dev:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/expo:dev: ERROR: command finished with error: command (/project/t3-turbo-and-clerk/apps/expo) pnpm run dev exited (1)
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed with exit code 1.
```

Seems like expo that came with the template isn't updating all dependencies properly,

Ran recommended fix
`pnpx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0 react@18.1.0 react-dom@18.1.0`
After cd into `/apps/expo`

Still doesn't fix the issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ventura 13.0
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Pro Max

**Additional context**

**Comment by perkinsjr** [comment]
I cannot recreate this. This error happens when Expo attempts to install itself on a simulator. 

nothing to do with the template itself

Attempting on:

brand new Mac, new Xcode that has never had Expo used. Just got it today. 

windows 10 and another macbook.

Will try and dig around the internet for a solution.

**Comment by wmendes** [comment]
Exactly same problem here.

**Comment by perkinsjr** [comment]
Can you give me the Xcode version and XCode command line #

What steps you attempted to fix it if any.


This is unrelated to the template but related for Expo and how it attempts to install the Expo Go package.

Does running

npm run start from the expo directory and pressing i resolve it?

basically more info the better

**Comment by mihai-ursu** [comment]
A fix for this is to log in to a google account on the simulator and install expo go on it. That is what I did on Windows and the app just works after.

**Comment by perkinsjr** [comment]
> A fix for this is to log in to a google account on the simulator and install expo go on it. That is what I did on Windows and the app just works after.

This is indeed the fix, however it should only happen rarely when expo go can't be installed and it should be installed if it doesn't exist. So keeping this open while I investigate some solutions.

**Comment by mtapiafdez** [comment]
The problem happens, because the expo go application is not installing. I am not sure where we could place this in the process, maybe install, but installing the iOS client (expo client:install:ios) did the trick for me.

**Comment by yiannis-pan** [comment]
Same problem here. I did a typical expo app to get the expo go app on the simulator, but then i was getting this: 
 Opening exp://192.168.2.4:19000 on iPhone 14 Pro
```
@acme/expo:dev: CommandError: Input is required, but 'npx expo' is in non-interactive mode.
@acme/expo:dev: Required input:
@acme/expo:dev: > Expo Go on iPhone 14 Pro is outdated, would you like to upgrade?
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
```

**Comment by yiannis-pan** [comment]
Had the same issue.
Going to the expo dir and running npm start and then pressing i to run on simulator installed the app. 
Since, pnpm dev works just fine

**Comment by perkinsjr** [comment]
Closing this as there isn't anything to actively do.
