### ISSUE TITLE
unhandled exception caused huge confusion when building a standalone app

### ISSUE THREAD

**Issue by michelsafi** [clerkinc/t3-turbo-and-clerk#45]
in expo/src/utils/trpc.tsx on line 31, there is an unhandled exception. this exception is not thrown when using the expo go app.
however when i built a standalone app, this exception was thrown, making the app freeze on the splash screen.
it took me a lot of time to figure out what was the issue. to save others time, please handle this exception.

**Comment by perkinsjr** [comment]
Can you provide exact steps to repro?

Can you provide screen shots, logs, versions etc? 

The Bug template should of been used so we have all the details we need.

**Comment by michelsafi** [comment]
Describe the bug
Android Preview build using expo eas getting stuck on splash screen after login. The issue does not occur when developing using the Expo Go app.

To Reproduce
1. Add a preview build to eas.json:
{
  "cli": {
    "version": ">= 3.3.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk",
        "gradleCommand": ":app:assembleRelease"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
2. Build a preview app for android using expo eas: eas build -p android --profile preview
3. Install apk on device
4. open the app
5. login using oauth
6. app will be stuck on splash screen

Expected behavior
App should not be stuck on splash screen

Device: Samsung S22 Ultra
OS: Android 12

**Comment by perkinsjr** [comment]
I cannot recreate this:

1. Set my OAuth in Clerk dashboard to the application redirect I expect e.g t3turbo://oath_callback.
2. Use the build above
3. Set my scheme in my app.config.ts 
4. Application builds, launches, and works as expected.

What did you do to fix your issue here / What did you do for your unhandled exception? This would only occur when misconfiguring your Expo application and I am trying to figure out the best way to mitigate this.

**Comment by jakewies** [comment]
It looks like the code in question is [here](https://github.com/clerkinc/t3-turbo-and-clerk/blob/main/apps/expo/src/utils/trpc.tsx#L31). I'm debugging an issue myself and wondering if this could be the cause.

In the [Deploy to Vercel section of the `README`](https://github.com/clerkinc/t3-turbo-and-clerk#deploy-to-vercel), #3, there is this:

> Assign your domain and use that instead of localhost for the url in the Expo app so that your Expo app can communicate with your backend when you are not in development.

I am wondering if this is the cause.

**Comment by jakewies** [comment]
Update - I was able to solve my issue by returning the deployed nextjs app's url in a preview expo build:

```ts
const getBaseUrl = () => {
  const localhost = Constants.manifest?.debuggerHost?.split(":")[0];
  if (!localhost) {
    return "your-nextjs-app-url.vercel.app";
  }
  return `http://${localhost}:3000`;
};
```
