### ISSUE TITLE
Navigation flickering when using Clerk in NextJS middleware to protect routes

### ISSUE THREAD

**Issue by EricDotSmith** [clerkinc/t3-turbo-and-clerk#49]
I have an app with multiple unprotected routes, like the following:

/dashboard
/settings

Navigating between them is seamless, with no flicking when clicking the button to go to each others page.

I now want to make these routes protected until the user is properly authenticated. I got this to work by following and tweaking the example here: https://clerk.dev/docs/nextjs/middleware

However, an undesirable effect started to happen to that original seamless navigation I once had before making those routes protected. There is a momentary flicker where the screen goes white for the briefest of a second then loads the page. 

Upon investigation and with a suggestion from the Clerk team, the flickering was fixed by upgrading from: "next": "^13.0.5", to "next": "^13.1.6".

There was a big improvement to middleware in NextJS 13.1 as seen here: https://nextjs.org/blog/next-13-1#nextjs-advanced-middleware.

### **Suggestion: Update NextJS for this repo to 13.1.6**

**Comment by perkinsjr** [comment]
This has been updated as well as updated the next config to move transpile out of experimental.
