### ISSUE TITLE
Build and configuration processes on Linux

### ISSUE THREAD

**Issue by semsion** [clerkinc/t3-turbo-and-clerk#52]
Thank you for a good looking build template.

Can anybody confirm if the build and configuration processes have been tested on Linux, and not just on macOS?

The question comes from testing fairly deep into tools such as these, and then later during testing realising that certain processes had not been tested on Linux, and fell into some compatibility issues.

Any clarification here would be much appreciated.

**Comment by perkinsjr** [comment]
This has been tested on a Linux, Windows and Macbook. 

The testing was very light (can you develop on the system) and building was done on Vercel and locally on Mac and Windows.

**Comment by semsion** [comment]
Thank you for the build and Dev info.
