### ISSUE TITLE
Authentication with Google and Apple doesn't work in Testflight

### ISSUE THREAD

**Issue by magnusrodseth** [clerkinc/t3-turbo-and-clerk#53]
**Describe the bug**

Authentication with Google and Apple doesn't work in Testflight. The user does not receive the pop-up with the auth redirection, and cannot sign in.

The project is bootstrapped, and I have not added any custom logic besides adding buttons for logging in with Google and Apple.

This works fine locally when using Expo Go, but not when launching a build in Testflight.

**To Reproduce**

1. Start a new repository from the template
2. Add Google and Apple as OAuth provider options
3. Set up an Expo project and hook it up to Apple Store Connect in order to submit the app to Testflight
4. Build the app, and submit it to Testflight
5. Open the application in Testflight
6. Observe that neither Google nor Apple let the user log in

**Expected behavior**

The user can log in using Google or Apple, both during development and whilst in Testflight.

**Logs**

There is no possibility for logs, as the Testflight build does not output anything.

Additionally, it works locally and does not error.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 
**Additional context**

Not sure this really is an issue with this repo, but I wanted to bring it up as a discussion ☺️ I believe it should be **very** easy to bootstrap a project and deploy it immediately.

**Comment by perkinsjr** [comment]
Please make sure you updated the code here. That needs to be set to your vercel deployment. 

https://github.com/clerkinc/t3-turbo-and-clerk/blob/main/apps/expo/src/utils/trpc.tsx#L31

**Comment by magnusrodseth** [comment]
I see ☺️ In the link you provided above, should it simply return the production URL? So:

```ts
...
const localhost = Constants.manifest?.debuggerHost?.split(":")[0];
  if (!localhost)
    return `https://path/to/production/url`;
  return `http://${localhost}:3000`;
```

**Comment by perkinsjr** [comment]
Yup exactly this.

**Comment by magnusrodseth** [comment]
@perkinsjr I can also submit a PR that specifies this in the `README`. Would you be keen?

**Comment by perkinsjr** [comment]
Sure:

It is stated:

> Done! Your app should successfully deploy. Assign your domain and use that instead of localhost for the url in the Expo app so that your Expo app can communicate with your backend when you are not in development.

Because there are a few different ways to assign this. 

1. Use a hardcode URL
2. Using Expo Config constants
3. Use Expo Env's

So we want to leave it broad as possible, however feel free to open a PR and I will review it.

**Comment by magnusrodseth** [comment]
@perkinsjr I now got around to deploying a new version of my demo Expo app in Testflight with the updated `getBaseUrl`, as we discussed. Neither authentication with Google nor Apple works. Please see the attached video for reference.

When I think about it, hooking the demo Expo app up to the production tRPC server wouldn't make a difference, as authentication with Clerk is not part of the tRPC layer. 

I have tested locally that both the Clerk secret key and public key are defined. I have also added these keys as environment variables in the deployed Next.js application on Vercel.

What are your thoughts on this? It is near impossible to debug what happens / not happens in Testflight.

https://user-images.githubusercontent.com/59113973/218518613-9332322f-03c5-4c92-93f5-d18ff8ea918a.mov

**Comment by perkinsjr** [comment]
Based on that my guess are, you didn't do one of the following:

1.Set my OAuth in Clerk dashboard to the application redirect I expect e.g t3turbo://oath_callback
2. Set my scheme in my app.config.ts to match.

**Comment by magnusrodseth** [comment]
Could you elaborate on both of these? I'm not sure I understand what you mean ☺️

**Comment by magnusrodseth** [comment]
No `https` before the `{scheme}://oauth-callback`, I reckon?

**Comment by perkinsjr** [comment]
Correct. our example shows a https request but it will be something like:

yourapp://oauth_callback

**Comment by magnusrodseth** [comment]
@perkinsjr Fantastic, it works! I'll submit a PR with some updated docs that inform developers of what we discovered in this thread. Thank you very much for the help and patience 😁

**Comment by neilk17** [comment]
I am having the same issue, I have added the scheme to my app.config as well as the the callback redirect URI,

It works for me on Dev but not on Testflight. 

Could you help me ?
