### ISSUE TITLE
Question about getServerSideProps and Prisma use here

### ISSUE THREAD

**Issue by EricDotSmith** [clerkinc/t3-turbo-and-clerk#55]
I have a situation where I want to call the server from getServerSideProps to see if something exists for a dynamic route, if not redirect to 404. I know tRPC can't be accessed from this method, so my question is, **is there any downsides to just using the global Prisma instance within getServerSideProps?** If not is there a better way to handle redirects where the dynamic route isn't available?

Currently, I'm importing prisma from 

`import { prisma } from "../../../../../packages/db";`

And using it in getServerSideProps

Thank you

**Comment by perkinsjr** [comment]
There is no downside. this should be fine to do.
