### ISSUE TITLE
Errors with initial run dev on Linux after install

### ISSUE THREAD

**Issue by semsion** [clerkinc/t3-turbo-and-clerk#56]
The initial pnpm install appeared to work okay, but when running pnpm run dev, a lot of errors are being returned.

### Of concern:

- The terminal output suggests using npx to install other dependencies, but wouldn't using npx conflict with pnpm?
- It also states that Xcode needs to be installed, however this is a Linux dev environment 

### Terminal output:

@acme/expo:dev: Some dependencies are incompatible with the installed expo version:
@acme/expo:dev:   @shopify/flash-list@1.4.0 - expected version: 1.3.1
@acme/expo:dev:   expo-auth-session@3.7.3 - expected version: ~3.8.0
@acme/expo:dev:   react@18.2.0 - expected version: 18.1.0
@acme/expo:dev:   react-dom@18.2.0 - expected version: 18.1.0
@acme/expo:dev: Your project may not work correctly until you install the correct versions of the packages.
@acme/expo:dev: Install individual packages by running npx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0 react@18.1.0 react-dom@18.1.0
@acme/db:dev: Prisma schema loaded from prisma/schema.prisma
@acme/db:dev: Prisma Studio is up on http://localhost:5556
@acme/expo:dev: Starting Metro Bundler
@acme/expo:dev: CommandError: Input is required, but 'npx expo' is in non-interactive mode.
@acme/expo:dev: Required input:
@acme/expo:dev: > Xcode needs to be installed (don't worry, you won't have to use it), would you like to continue to the App Store?
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/expo:dev: ERROR: command finished with error: command (<path-to_proj>/t3-turbo-and-clerk/apps/expo) pnpm run dev exited (1)
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed.

Please share any thoughts regarding these matters.

**Comment by perkinsjr** [comment]
This error occurs because you are attempting to run the pnpm run dev command. When running this we have it set to use iOS by default. The error is 

` Xcode needs to be installed (don't worry, you won't have to use it), would you like to continue to the App Store?` 

Because you are using Linux, you can set the app to use android by changing this package command

```
 "dev": "expo start --ios",
 ```
  To be 
 ``` 
 "dev": "expo start --android",
  ```
  
  Or if you plan to use a physical device:
  
  ```
   "dev": "expo start"
   ```

**Comment by semsion** [comment]
This partially resolved an initial run.

The package update issue was partially resolved with `pnpx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0 react@18.1.0 react-dom@18.1.0 -- -w`

There was also an error on the CLI stating `Cannot read properties of null (reading 'update')` - which appeared to be resolved by running `pnpm install expo-cli -- -w`

However, when visiting http://localhost:3000/ - the web app appears to be failing to compile, as follows:

../../packages/api/src/context.ts:4:0
Module not found: Can't resolve '@clerk/nextjs/server'
  2 | import { type inferAsyncReturnType } from "@trpc/server";
  3 | import { type CreateNextContextOptions } from "@trpc/server/adapters/next";
> 4 | import { getAuth, clerkClient } from "@clerk/nextjs/server";
  5 | import type { User } from "@clerk/nextjs/api";
  6 | /**
  7 |  * Replace this with an object if you want to pass things to createContextInner

Import trace for requested module:
../../packages/api/index.ts
./src/pages/api/trpc/[trpc].ts

https://nextjs.org/docs/messages/module-not-found

Any ideas out there!?

**Comment by perkinsjr** [comment]
```
The package update issue was partially resolved with pnpx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0 react@18.1.0 react-dom@18.1.0 -- -w
```

This is untested and a reason we haven't updated all packages at thsi time. However looks like it didn't install the packages correctly. 

So you can go to the root and do `pnpm clean:workspaces` and then run `pnpm i` and then run `pnpm run dev`

**Comment by semsion** [comment]
Thank you for the suggestion, however after `pnpm clean:workspaces` `pnpm i` and `pnpm run dev` the the web app at http://localhost:3000/ is still showing the same error. 

Some other CLI errors that may be related:

`@acme/expo:dev: WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).`

```
@acme/expo:dev: [23:41:19] Some dependencies are incompatible with the installed expo package version:
@acme/expo:dev: [23:41:19]  - @shopify/flash-list - expected version: 1.3.1 - actual version installed: 1.4.0
@acme/expo:dev: [23:41:19]  - expo-auth-session - expected version: ~3.8.0 - actual version installed: 3.7.3
@acme/expo:dev: [23:41:19]  - react - expected version: 18.1.0 - actual version installed: 18.2.0
@acme/expo:dev: [23:41:19]  - react-dom - expected version: 18.1.0 - actual version installed: 18.2.0
@acme/expo:dev: [23:41:19] Your project may not work correctly until you install the correct versions of the packages.
@acme/expo:dev: To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
@acme/expo:dev: or install individual packages by running expo install [package-name ...]
```

Screenshot of the web app error from localhost:

![image](https://user-images.githubusercontent.com/15907315/222008770-dcff2786-7bce-4803-983c-29dcfc0a05f2.png)

**Comment by perkinsjr** [comment]
those are warnings and only matched to Expo... which isn't related to Next.js

can you confirm that the node modules exist where they should? 

if you go to that file are there errors. 

this error is related to not installing node modules.

have you tried deleting and checking out a fresh copy and attempting it?
