### ISSUE TITLE
trpc.useContext is missing many helper functions

### ISSUE THREAD

**Issue by EricDotSmith** [clerkinc/t3-turbo-and-clerk#57]
Why are there many missing methods that should be within the trpc context. The only one appearing is invalidate.

<img width="500" alt="Screenshot 2023-02-22 at 4 49 53 PM" src="https://user-images.githubusercontent.com/67427202/220767699-f4b4790e-1c72-423f-9d7c-479809b88ce7.png">

Meanwhile in the trpc docs there should be many more:

<img width="500" alt="Screenshot 2023-02-22 at 4 50 46 PM" src="https://user-images.githubusercontent.com/67427202/220767908-fe599b47-d9c0-4bdf-816a-5ee2dcee656e.png">

Not exactly sure why this is happening so any help will be appreciated. Also I know that I can use react query directly to do what I want to, but I'd rather use tRPCs helpers.

**Comment by perkinsjr** [comment]
This isn't a bug. 

This is how TRPC works, you can access all of those helpers with your context provided in your router for example:

![image](https://user-images.githubusercontent.com/45409975/220771074-5a8cf1c1-ab7d-443d-a57a-b080171bb4fa.png)

Per the docs:

> useContext returns an object with all the available queries you have in your routers. You use it the same way as your trpc client object. Once you reach a query, you'll have access to the query helpers. 

https://trpc.io/docs/useContext#usage

We aren't doing anything with TRPC it's vanilla and implemented by the TRPC core team.
