### ISSUE TITLE
Middleware parsing error and refresh loop

### ISSUE THREAD

**Issue by matteobad** [clerkinc/t3-turbo-and-clerk#58]
**Describe the bug**
Hi, I've been working with the T3 turbo template with Clerk in a project and this was a great reference, but there was a small, non-blocking, problem that I opened here: https://github.com/clerkinc/javascript/issues/840 and that was fixed pretty quickly.

Now the error mentioned in the above issue is gone, but every page gets stuck in a loading loop triggered by some clerk script tag in the html (screenshot below). I'm reporting things here because this template gives me the exact same errors.

**To Reproduce**
1. Update `@clerk/nextjs` to `4.11.0`
2. Go to homepage
3. Sign In
4. See the refresh loop

**Expected behavior**
No error in the middleware and no refresh loop

**Screenshots**
The refresh that causes the loop
<img width="1440" alt="Schermata 2023-02-24 alle 14 38 20" src="https://user-images.githubusercontent.com/10132048/221192585-9857687f-0c65-4010-b199-03301a73ba05.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.2 (21G320)
 - Browser chrome, safari
 - Version 110.0.5481.100 (Build ufficiale) (x86_64)

**Additional context**
Old issue present in the template: https://github.com/clerkinc/javascript/issues/840
New issue after updating the library: refresh loop

**Comment by perkinsjr** [comment]
Can you please update to 4.11.0 which was released today. This isn't related to T3-Turbo-and Clerk but clerk itself.

**Comment by perkinsjr** [comment]
Closing this in favor of the issue you opened in the core javascript lib.

https://github.com/clerkinc/javascript/issues/865
