### ISSUE TITLE
Expo 48 Support

### ISSUE THREAD

**Issue by siddharthsharma94** [clerkinc/t3-turbo-and-clerk#60]
Would be great to use this with the new [expo routes package](https://blog.expo.dev/expo-sdk-48-ccb8302e231)

The official [t3-turbo](https://github.com/t3-oss/create-t3-turbo) also added support for expo router

**Comment by perkinsjr** [comment]
We currently don't support Expo 48 with the Clerk Expo package. When we add that we will introduce Expo routes at the same time.

**Comment by neolivz** [comment]
Is there anywhere I can track when Clerk will support expo 48 with Expo router?

**Comment by perkinsjr** [comment]
this issue as when it’s ready i’ll notify people it’s supported

Sent via Superhuman iOS ***@***.***>

**Comment by perkinsjr** [comment]
Hey @neolivz and @siddharthsharma94 I added support for Expo 48 with full support for OAuth.

I am going to add Expo Router support after the fact as I have to rewrite the code base a bit (probably on Monday you will se this)

**Comment by perkinsjr** [comment]
Hey @neolivz and @siddharthsharma94 me again!

https://github.com/clerkinc/t3-turbo-and-clerk/tree/expo-router

This Branch runs expo router that you can test against, until I decide when to merge
