### ISSUE TITLE
Not showing google accounts list

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [clerkinc/t3-turbo-and-clerk#62]
**Describe the bug**

**To Reproduce**
1. Configure clerk dashboard to accept `google`
2. Change to `oauth_google`

**Expected behavior**
Should show the common google accounts list to log in as any other app

**Logs**
Please provide logs showing the error.

**Screenshots**
<img width="431" alt="Screenshot 2023-03-02 at 21 44 02" src="https://user-images.githubusercontent.com/74371045/222618346-52773a05-3d84-45c6-b933-93edeac3436c.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro max

**Additional context**
I'm not entirely sure if it's an bug but would like to know why that happens, haven't found anything in the docs

**Comment by perkinsjr** [comment]
This is a protective layer by Expo  which was introduced recently in s more obvious way, once you go through you will the google accounts screen.

This is expo auth proxy code and not related to Clerk in anyway.

**Comment by AlvaroAquijeDiaz** [comment]
will this appear on the production app as well? In case I deploy to the app store with EAS

**Comment by perkinsjr** [comment]
No when you setup a production / standalone development build and follow all the steps in the README.md / also create your expo application correctly you won't see this.
