### ISSUE TITLE
Possible unhandled promise rejection (id: 0):

### ISSUE THREAD

**Issue by Clint1080** [clerkinc/t3-turbo-and-clerk#64]
**Describe the bug**
I have followed all of steps in the readme up to the Deployment section.  I am trying to get this running on the simulators for both android and apple.   The bug happens when running ```pnpm run android``` or ```pnpm run ios```.  After running either command prisma studio opens and runs.  Then the either simulator will open and show the purple T3 logo while building the bundle.   As soon as the bundle is done building I see the error. 

**To Reproduce**
1. Navigate to /apps/expo/ run ```pnpm run ios``` or ```pnpm run android```
2. Wait for either simulator to start.
3. see T3 turbo logo while building the bundle. 
4. see the error.   

**Expected behavior**
I expected to get to the home page like in the youtube videos.

**Logs**
Please provide logs showing the error.
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error
throwError@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:110669:26
@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:110654:28
generatorResume@[native code]
asyncGeneratorStep@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:21024:26
_throw@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:21046:29
tryCallOne@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:25531:16
@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:25612:27
@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:26507:26
_callTimer@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:26426:17
_callReactNativeMicrotasksPass@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:26456:17
callReactNativeMicrotasks@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:26619:44
__callReactNativeMicrotasks@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:20162:46
@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:19974:45
__guard@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:20146:15
flushedQueue@http://192.168.86.244:19001/index.ts.bundle?platform=ios&dev=true&hot=false:19973:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]```
**Screenshots**
If applicable, add screenshots to help explain your problem.
![Screenshot_1679185169](https://user-images.githubusercontent.com/20569254/226146949-5087c7ea-207b-4b90-bba6-f171df862bfa.png)


**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.2.1
 - Browser xcode or android studio
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
I cloned the repo on 3-18-2023
If I dismiss the error I just have a blank screen

**Comment by perkinsjr** [comment]
If you run `pnpm run dev` from the root of the project which launches next.js / prisma / TRPC api end points etc. Do you see this error? I am unable to recreate this.

**Comment by Clint1080** [comment]
Yeah I have the same issue.  Prisma studio starts up and works but then as soon as the bundle is done I get that same error. I'm not sure what I'm doing wrong I've followed to readme exactly.

**Comment by Clint1080** [comment]
I previously cloned the repo about a month ago and I have been able to get that one working for web and ios but I still can't get it it to work for android.  It must be something i'm doing wrong.  Thanks for your time!
