### ISSUE TITLE
Cannot find module '@expo/config-plugins'

### ISSUE THREAD

**Issue by hunght** [clerkinc/t3-turbo-and-clerk#67]
I setup the eas config then run ``eas build --platform android --profile preview`` it failed with error 
![Screenshot 2023-04-03 at 12 11 11](https://user-images.githubusercontent.com/1697756/229416900-8df87fc3-dc64-432e-be54-0d141cbd8ad1.png)
could you help check that?

**Comment by perkinsjr** [comment]
This happens when packages don't get installed correctly. 

run 
pnpm clean:workspaces 
pnpm clean
pnpm i
