### ISSUE TITLE
Unable to communicate with Prisma Client.

### ISSUE THREAD

**Issue by indicozy** [clerkinc/t3-turbo-and-clerk#70]
**Describe the bug**
On pnpm dev prisma studio opens and throws error:
```
Unable to communicate with Prisma Client. Is Studio still running? You may need to restart it using `npx prisma studio`
TypeError: NetworkError when attempting to fetch resource.
```

But if I will write `pnpx prisma studio --schema packages/db/prisma/schema.prisma` everything works fine.

**Comment by perkinsjr** [comment]
I am unable to recreate this either. Going to close this and just handle it all in one issue #69
