### ISSUE TITLE
Google auth in nextjs app not redirecting back to app

### ISSUE THREAD

**Issue by timmeade** [clerkinc/t3-turbo-and-clerk#73]
**Describe the bug**
I may have just went to far with clerk and am missing a config step

i created my clerk account and upgraded to helper and add org.   
Created the org and app and added google, github, email to auth methods
I pulled everything into the new monorepo.

App starts ok and login works via my google account
Clerk acknowledges the user exists and congratulated me.

App does not redirect back to my app, but instead seems to be a new clerk.dev account page with the following in purple at bottom of page:

```
You are signed in, but Clerk cannot redirect to your application
```

No idea what to do now.  Searching for google and redirect and nothing....

**Comment by perkinsjr** [comment]
This isn't an issue with this project please go to https://clerk.com/support and reach out to the support team. 

This usually occurs if we cannot redirect you back to the page you started on. I tested this just now and everything is working as expected.
