### ISSUE TITLE
"Not authenticated" when using tRPC useMutation

### ISSUE THREAD

**Issue by ringge** [clerkinc/t3-turbo-and-clerk#77]
**Describe the bug**
This is only about the nextjs app portion. I started freshly from the template, then tried a simple tRPC mutation request like this: Added a Button, when clicked, a tRPC mutation request is run to fetch the posts from database, however the request showed error: "Not authenticated".  

**To Reproduce**
1. Used the t3-turbo-and-clerk template 
2. Created account on Clerk.com and created an app, using Production branch, added the domain, do everything as required on the Dashboard, then obtain the Clerk production keys to be added to .env
3. Added DATABASE_URL and Clerk production keys to .env
4. Since I'm not building the app on Vercel, rather I build it on my VPS (I tried both through CI/CD and manually command to build), so I adjusted 2 below lines in apps/nextjs/package.json so that build and start have access to .env
"build": "next build" -> to "build": "pnpm with-env next build",
"start: "next start" -> to "start": "pnpm with-env next start -p 3800",
5. at root folder run pnpm db-push, then pnpm --filter nextjs build
6. at root folder run pnpm --filter nextjs start

**Expected behavior**
after signing in, tRPC mutation requests are expected to be authorized and to work normally 

**Logs**
`POST
[HTTP/1.1 401 Unauthorized 255ms]
 << mutation #3 post.all  
Object { input: undefined, result: TRPCClientError, elapsedMs: 270, context: {} }
context: Object {  }
elapsedMs: 270
input: undefined
result: TRPCClientError: Not authenticated
cause: undefined
columnNumber: 24028
data: Object { code: "UNAUTHORIZED", httpStatus: 401, path: "post.all" }
fileName: "https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js"
lineNumber: 20
message: "Not authenticated"
meta: Object { response: Response }
name: "TRPCClientError"
shape: Object { message: "Not authenticated", code: -32001, data: {…} }
stack: "g@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:24028\nfrom@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:23940\n7576/k/</</</<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:27984\npromise callback*7576/k/</</<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:27439\nsubscribe@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:23443\nsubscribe@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:72476\n7576/config/<.links</<.links</<.links<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:72604\nsubscribe@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:23443\n7576/$request/o<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:737\nsubscribe@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:20:23443\nsubscribe@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:834\n7576/requestAsPromise/r<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:1299\n@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:1183\nrequestAsPromise@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:1412\nmutation@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:1679\n7576/eW/useMutation/u<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:31651\nfn@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:19609\ny@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:7806\nea@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:8194\n7576/execute/c<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:19561\nexecute@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:19979\nasync*mutate@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:22804\n7576/eW/useMutation/u<@https://rakno.tk/_next/static/chunks/pages/_app-17007621bf9dbe08.js:24:31469\nr@https://rakno.tk/_next/static/chunks/pages/index-9a4f1198fe969615.js:1:645\neU@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:14912\neH@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:15066\n2967/re/<@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:33374\nre@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:33473\nrn@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:33889\n2967/ro/<@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:39347\noP@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:96345\neF@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:14046\nro@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:35180\nnU@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:20849\nnD@https://rakno.tk/_next/static/chunks/framework-19f3649580393c10.js:9:20631\n"
<prototype>: Object { stack: "", … }
<prototype>: Object { … }`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.02
 - Browser Firefox
 - Version 112.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ebg1223** [comment]
This is happening on google cloud run as well. Fixed by downgrading to nextjs 13.3. Seems to be an incompatibility between nextjs 13.4 and clerk.

**Comment by perkinsjr** [comment]
Clerk works with next.js 13.4.1 and has no issues reading context. I just tested this in a tRPC application with succesful usage of both public and protected routes.

Can you reach out to support via https://clerk.com/support. The error itself doesn't look like anything related to this template.

**Comment by ringge** [comment]
Just in case any one bumped on this issue, the fix is by using these settings in nginx reverse proxy (copied from a support thread on Clerk's Discord)

proxy_pass http://localhost:3000/;
 proxy_http_version 1.1;
 proxy_set_header X-Forwarded-Host $host;
 proxy_set_header X-Forwarded-Server $host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header Host $http_host;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "Upgrade";
 proxy_pass_request_headers on;
