### ISSUE TITLE
pnpm db-push  fails 

### ISSUE THREAD

**Issue by MSturges** [clerkinc/t3-turbo-and-clerk#87]
Steps 
- clone repo
- updated env variables
- changed my prisma to point to existing db 
- updated prismaschema with mine that works find in other app
- pnpm i
- pnpm db-push

Seems like 'pnpm i' doesn't install node modules for db?  

Terminal Log:

• Packages in scope: @acme/api, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running db-push in 5 packages
• Remote caching disabled
@acme/db:db-push: cache bypass, force executing 6d43fc0dce4fb9fb
@acme/db:db-push: 
@acme/db:db-push: > @acme/db@0.1.0 db-push /Users/investment/packages/db
@acme/db:db-push: > pnpm with-env prisma db push
@acme/db:db-push: 
@acme/db:db-push: 
@acme/db:db-push: > @acme/db@0.1.0 with-env /Users/investment/packages/db
@acme/db:db-push: > dotenv -e ../../.env -- "prisma" "db" "push"
@acme/db:db-push: 
@acme/db:db-push: Prisma schema loaded from prisma/schema.prisma
@acme/db:db-push: Datasource "db": MySQL database "investing-app" at "aws.connect.psdb.cloud"
@acme/db:db-push: 
@acme/db:db-push: Error: Migration engine error:
@acme/db:db-push: unknown error: Code: UNAVAILABLE
@acme/db:db-push: server does not allow insecure connections, client must use SSL/TLS
@acme/db:db-push: 
@acme/db:db-push: 
@acme/db:db-push:  ELIFECYCLE  Command failed with exit code 1.
@acme/db:db-push:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
@acme/db:db-push:  ELIFECYCLE  Command failed with exit code 1.
@acme/db:db-push:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
@acme/db:db-push: ERROR: command finished with error: command (/Users/investment/packages/db) pnpm run db-push exited (1)
command (/Users/investment/packages/db) pnpm run db-push exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.638s 
Failed:    @acme/db#db-push

**Comment by MSturges** [comment]
nvm i made a mistake in my env.

**Comment by mundume** [comment]
im having this issue too idk whats wrong tbh
